export default {
  at: '2023-03-11T12:48:34.551Z',
  products: [
    {
      description: 'aliqua minim proident Lorem',
      name: 'et',
      price: 1133.03,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {},
    {},
    {},
    {},
    {
      description: 'eiusmod dolore quis adipisicing',
      name: 'cillum',
      price: 397.9,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'deserunt aute fugiat sint',
      name: 'exercitation',
      price: 1810.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex eiusmod mollit ullamco',
      name: 'amet',
      price: 288.48,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: 'veniam dolore excepteur excepteur',
      name: 'pariatur',
      price: 832.24,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {},
    {},
    {},
    {},
    {
      description: 'reprehenderit Lorem consequat commodo',
      name: 'eu',
      price: 1040.83,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'tempor velit excepteur est',
      name: 'sunt',
      price: 1678.58,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua officia quis magna',
      name: 'voluptate',
      price: 1637.34,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {},
    {},
    {},
    {},
    {
      description: 'ullamco mollit aute veniam',
      name: 'irure',
      price: 1677.02,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: 'nisi velit aliqua qui',
      name: 'reprehenderit',
      price: 1953.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'fugiat fugiat esse magna',
      name: 'magna',
      price: 1777.91,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'Lorem reprehenderit cillum incididunt',
      name: 'proident',
      price: 729.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consectetur deserunt ad occaecat',
      name: 'exercitation',
      price: 604.6,
      tmpProperty: undefined,
      activePromoId: 3,
    },
    {
      description: 'magna deserunt eiusmod id',
      name: 'labore',
      price: 1707.03,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: 'elit minim culpa anim',
      name: 'fugiat',
      price: 957.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit quis sunt labore',
      name: 'eu',
      price: 1257.73,
      tmpProperty: undefined,
      activePromoId: 27,
    },
    {
      description: 'reprehenderit culpa aliqua Lorem',
      name: 'nisi',
      price: 919.67,
      tmpProperty: undefined,
      activePromoId: 63,
    },
    {
      description: 'ex officia aute id',
      name: 'non',
      price: 578.31,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum laborum anim pariatur',
      name: 'sunt',
      price: 659.78,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: 'nulla magna proident fugiat',
      name: 'cillum',
      price: 1091.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consectetur esse aute pariatur',
      name: 'do',
      price: 1937.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse in exercitation labore',
      name: 'aute',
      price: 1366.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco qui et dolor',
      name: 'ea',
      price: 1660.72,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: 'sit laborum est proident',
      name: 'consectetur',
      price: 1611.35,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: 'proident exercitation adipisicing ullamco',
      name: 'cillum',
      price: 1806.05,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: 'quis mollit cupidatat quis',
      name: 'id',
      price: 290.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'enim id amet ipsum',
      name: 'voluptate',
      price: 1126.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'id eu reprehenderit non',
      name: 'cillum',
      price: 1775.1,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: 'esse eu ut ipsum',
      name: 'sit',
      price: 1258.74,
      tmpProperty: undefined,
      activePromoId: 9,
    },
    {
      description: 'culpa et proident ullamco',
      name: 'cillum',
      price: 972.93,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'excepteur sunt occaecat eiusmod',
      name: 'aliquip',
      price: 1247.68,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: 'eiusmod id Lorem excepteur',
      name: 'aute',
      price: 1815.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ex nostrud sint non',
      name: 'commodo',
      price: 822.9,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'mollit occaecat voluptate commodo',
      name: 'non',
      price: 1571.21,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: 'magna consequat labore consectetur',
      name: 'ad',
      price: 476.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit esse veniam Lorem',
      name: 'occaecat',
      price: 105.14,
      tmpProperty: undefined,
      activePromoId: 63,
    },
    {
      description: 'nostrud ullamco ex ipsum',
      name: 'veniam',
      price: 1195.84,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: 'ipsum eu velit cillum',
      name: 'sint',
      price: 1765.14,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aute commodo cupidatat duis',
      name: 'fugiat',
      price: 519.88,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: 'quis adipisicing consectetur dolor',
      name: 'excepteur',
      price: 1102.18,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: 'incididunt minim adipisicing mollit',
      name: 'exercitation',
      price: 400.96,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: 'culpa et tempor culpa',
      name: 'voluptate',
      price: 402.32,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: 'aliqua esse labore aliquip',
      name: 'ullamco',
      price: 1026.67,
      tmpProperty: undefined,
      activePromoId: 55,
    },
    {
      description: 'Lorem quis qui aute',
      name: 'reprehenderit',
      price: 770.27,
      tmpProperty: undefined,
      activePromoId: 62,
    },
    {
      description: 'laborum duis nostrud esse',
      name: 'laboris',
      price: 1183.93,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'fugiat dolor laborum do',
      name: 'eu',
      price: 900.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'non aliquip ut in',
      name: 'duis',
      price: 1775.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'Lorem occaecat pariatur pariatur',
      name: 'pariatur',
      price: 787.47,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'labore tempor ex magna',
      name: 'elit',
      price: 891.97,
      tmpProperty: undefined,
      activePromoId: 96,
    },
    {
      description: 'tempor culpa cillum id',
      name: 'deserunt',
      price: 1998.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'id deserunt consectetur non',
      name: 'qui',
      price: 141.21,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: 'esse incididunt culpa veniam',
      name: 'do',
      price: 1316.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cillum id cillum exercitation',
      name: 'in',
      price: 104.34,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: 'exercitation ut aliqua nostrud',
      name: 'aliqua',
      price: 977.41,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: 'aliqua dolore labore aute',
      name: 'est',
      price: 1826.47,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: 'non eu Lorem non',
      name: 'exercitation',
      price: 1290.27,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: 'occaecat sit mollit laborum',
      name: 'ullamco',
      price: 945.35,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: 'elit esse excepteur et',
      name: 'in',
      price: 1167.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'et ad id commodo',
      name: 'cupidatat',
      price: 970.69,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: 'aliquip et pariatur exercitation',
      name: 'eiusmod',
      price: 495.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation sint elit culpa',
      name: 'ullamco',
      price: 1992.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint pariatur qui amet',
      name: 'quis',
      price: 1257.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad nulla Lorem officia',
      name: 'excepteur',
      price: 852.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'fugiat id mollit quis',
      name: 'dolor',
      price: 812.86,
      tmpProperty: undefined,
      activePromoId: 21,
    },
    {
      description: 'incididunt amet do incididunt',
      name: 'ea',
      price: 256.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'duis enim non ea',
      name: 'do',
      price: 1340.62,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: 'voluptate adipisicing tempor sit',
      name: 'occaecat',
      price: 1640.42,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse nostrud ipsum tempor',
      name: 'amet',
      price: 1920.36,
      tmpProperty: undefined,
      activePromoId: 47,
    },
    {
      description: 'minim cillum ipsum aliquip',
      name: 'nisi',
      price: 396.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation voluptate anim incididunt',
      name: 'aliqua',
      price: 1513.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'pariatur et nostrud exercitation',
      name: 'dolore',
      price: 442.72,
      tmpProperty: undefined,
      activePromoId: 40,
    },
    {
      description: 'pariatur proident in qui',
      name: 'veniam',
      price: 909.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'incididunt mollit irure occaecat',
      name: 'Lorem',
      price: 1182.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliquip minim et consectetur',
      name: 'ea',
      price: 450.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'Lorem sunt elit occaecat',
      name: 'deserunt',
      price: 884.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo cillum esse sunt',
      name: 'ullamco',
      price: 461.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cillum id id eiusmod',
      name: 'non',
      price: 870.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eiusmod nisi magna dolor',
      name: 'irure',
      price: 1698.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'qui ex dolor ad',
      name: 'eu',
      price: 655.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad ex cupidatat velit',
      name: 'non',
      price: 1234.79,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: 'cupidatat laborum ea eu',
      name: 'aliquip',
      price: 1635.86,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: 'nostrud ea amet cillum',
      name: 'sit',
      price: 1838.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'proident elit nisi cupidatat',
      name: 'dolor',
      price: 630.42,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: 'sint ullamco irure Lorem',
      name: 'aliqua',
      price: 991.05,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'tempor pariatur ea fugiat',
      name: 'dolor',
      price: 670.35,
      tmpProperty: undefined,
      activePromoId: 49,
    },
    {
      description: 'elit Lorem nulla elit',
      name: 'magna',
      price: 1196.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit exercitation minim aute',
      name: 'amet',
      price: 1163.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ut ullamco occaecat Lorem',
      name: 'ex',
      price: 565.26,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: 'labore fugiat magna consequat',
      name: 'consequat',
      price: 1436.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'eu duis pariatur deserunt',
      name: 'pariatur',
      price: 1143.59,
      tmpProperty: undefined,
      activePromoId: 97,
    },
    {
      description: 'consequat velit aliquip non',
      name: 'nulla',
      price: 157.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'anim est cupidatat est',
      name: 'laborum',
      price: 124.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'culpa anim Lorem anim',
      name: 'do',
      price: 1245.19,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'labore nulla exercitation ex',
      name: 'magna',
      price: 1693.13,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'voluptate ipsum qui veniam',
      name: 'duis',
      price: 796.02,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'excepteur sunt aute elit',
      name: 'laborum',
      price: 926.82,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: 'voluptate irure officia aliqua',
      name: 'eu',
      price: 905.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum dolor duis enim',
      name: 'culpa',
      price: 1413.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'irure dolore nostrud ullamco',
      name: 'velit',
      price: 235.49,
      tmpProperty: undefined,
      activePromoId: 41,
    },
    {
      description: 'aute anim mollit proident',
      name: 'aute',
      price: 1921.98,
      tmpProperty: undefined,
      activePromoId: 50,
    },
  ],
};
